@extends('layouts.app')
@section('title', $document->title)
@section('content')
<div class="dashboard-page">
    @if (session('status'))<p class="dashboard-success" role="status">{{ session('status') }}</p>@endif
    @if (session('error'))<p class="dashboard-error" role="alert">{{ session('error') }}</p>@endif
    <x-ui.page-header :title="$document->title" :subtitle="'By ' . ($document->author?->name ?? 'Former member') . ' · ' . $document->created_at?->format('M j, Y')">
        <x-slot:actions><div class="article-badges"><x-ui.status-badge :status="$document->approval_status" />@if ($document->isArchived())<x-ui.status-badge status="archived" />@endif</div></x-slot:actions>
    </x-ui.page-header>
    @if ($document->isArchived())<p class="dashboard-notice">This document is archived and does not appear in Published.</p>@endif
    @if ($document->isPending())<p class="dashboard-notice">This document is pending adviser review.</p>@endif
    @if ($document->isRejected() && $document->rejection_reason)<p class="dashboard-error">Rejection reason: {{ $document->rejection_reason }}</p>@endif
    <section class="dashboard-panel"><p><strong>Category:</strong> {{ $document->category ?: 'Uncategorized' }}</p><p><strong>PDF:</strong> {{ $document->original_name }} ({{ number_format($document->file_size / 1024, 1) }} KB)</p>@if ($document->description)<div>{{ nl2br(e($document->description)) }}</div>@endif</section>
    {{-- SECURITY: File links appear only for authorized users; file routes authorize again before disk access. --}}
    <div class="article-actions">@can('viewFile', $document)<a class="dashboard-button" href="{{ route('documents.view', $document) }}">View PDF</a>@endcan @can('download', $document)<a class="dashboard-button dashboard-button-secondary" href="{{ route('documents.download', $document) }}">Download</a>@endcan @guest<a class="dashboard-button" href="{{ route('documents.view', $document) }}">View PDF</a><a class="dashboard-button dashboard-button-secondary" href="{{ route('documents.download', $document) }}">Download</a>@endguest @can('update', $document)<a class="dashboard-button dashboard-button-secondary" href="{{ route('documents.edit', $document) }}">Edit</a>@endcan
        @can('archive', $document) @if (! $document->isArchived())<form id="archive-document-form" method="POST" action="{{ route('documents.archive', $document) }}">@csrf</form><button class="dashboard-button dashboard-button-secondary" type="button" onclick="document.getElementById('archive-document-modal').showModal()">Archive</button>@endif @endcan
        @can('restore', $document) @if ($document->isArchived())<form id="restore-document-form" method="POST" action="{{ route('documents.restore', $document) }}">@csrf</form><button class="dashboard-button dashboard-button-secondary" type="button" onclick="document.getElementById('restore-document-modal').showModal()">Restore</button>@endif @endcan
        @can('approve', $document) @if ($document->isPending())<form method="POST" action="{{ route('documents.approve', $document) }}">@csrf<button class="dashboard-button" type="submit">Approve</button></form><button class="dashboard-button dashboard-button-secondary" type="button" data-modal-open="document-reject-modal">Reject</button>@endif @endcan
        @can('delete', $document)<form id="delete-document-form" method="POST" action="{{ route('documents.destroy', $document) }}">@csrf @method('DELETE')</form><button class="dashboard-button dashboard-button-secondary" type="button" onclick="document.getElementById('delete-document-modal').showModal()">Delete</button>@endcan
    </div>
    @can('reject', $document) @if ($document->isPending())<x-ui.reject-modal id="document-reject-modal" :action="route('documents.reject', $document)" subject="document" />@endif @endcan
    @can('archive', $document) @if (! $document->isArchived())<dialog id="archive-document-modal" class="reject-modal"><div class="reject-modal-content"><h2>Archive document?</h2><p>The document leaves Published and keeps its approval state.</p><div class="reject-modal-actions"><button type="button" class="dashboard-button dashboard-button-secondary" onclick="document.getElementById('archive-document-modal').close()">Cancel</button><button type="submit" form="archive-document-form" class="dashboard-button">Archive</button></div></div></dialog>@endif @endcan
    @can('restore', $document) @if ($document->isArchived())<dialog id="restore-document-modal" class="reject-modal"><div class="reject-modal-content"><h2>Restore document?</h2><p>Its approval state will stay unchanged.</p><div class="reject-modal-actions"><button type="button" class="dashboard-button dashboard-button-secondary" onclick="document.getElementById('restore-document-modal').close()">Cancel</button><button type="submit" form="restore-document-form" class="dashboard-button">Restore</button></div></div></dialog>@endif @endcan
    @can('delete', $document)<dialog id="delete-document-modal" class="reject-modal"><div class="reject-modal-content"><h2>Delete document permanently?</h2><p>This also removes its private PDF file and cannot be undone.</p><div class="reject-modal-actions"><button type="button" class="dashboard-button dashboard-button-secondary" onclick="document.getElementById('delete-document-modal').close()">Cancel</button><button type="submit" form="delete-document-form" class="dashboard-button">Delete permanently</button></div></div></dialog>@endcan
</div>
@endsection
