@extends('layouts.app')
@section('title', $liquidation->title)
@section('content')
<div class="dashboard-page">
    @if (session('status'))<p class="dashboard-success" role="status">{{ session('status') }}</p>@endif
    @if (session('error'))<p class="dashboard-error" role="alert">{{ session('error') }}</p>@endif
    <x-ui.page-header :title="$liquidation->title" :subtitle="'By ' . ($liquidation->author?->name ?? 'Former member') . ' · ' . $liquidation->created_at?->format('M j, Y')"><x-slot:actions><div class="article-badges"><x-ui.status-badge :status="$liquidation->approval_status" />@if ($liquidation->isArchived())<x-ui.status-badge status="archived" />@endif</div></x-slot:actions></x-ui.page-header>
    @if ($liquidation->isArchived())<p class="dashboard-notice">This report is archived and does not appear in Published.</p>@endif
    @if ($liquidation->isPending())<p class="dashboard-notice">This report is pending adviser review.</p>@endif
    @if ($liquidation->isRejected() && $liquidation->rejection_reason)<p class="dashboard-error">Rejection reason: {{ $liquidation->rejection_reason }}</p>@endif
    <section class="dashboard-panel"><p><strong>Amount:</strong> {{ $liquidation->formattedAmount() }}</p><p><strong>Report date:</strong> {{ $liquidation->report_date?->format('M j, Y') ?? 'Not provided' }}</p><p><strong>PDF:</strong> {{ $liquidation->original_name }} ({{ number_format($liquidation->file_size / 1024, 1) }} KB)</p>@if ($liquidation->description)<div>{{ nl2br(e($liquidation->description)) }}</div>@endif</section>
    {{-- SECURITY: Every PDF endpoint reauthorizes before reading the private disk. --}}
    <div class="article-actions">@can('viewFile', $liquidation)<a class="dashboard-button" href="{{ route('liquidations.view', $liquidation) }}">View PDF</a>@endcan @can('download', $liquidation)<a class="dashboard-button dashboard-button-secondary" href="{{ route('liquidations.download', $liquidation) }}">Download</a>@endcan @guest<a class="dashboard-button" href="{{ route('liquidations.view', $liquidation) }}">View PDF</a><a class="dashboard-button dashboard-button-secondary" href="{{ route('liquidations.download', $liquidation) }}">Download</a>@endguest @can('update', $liquidation)<a class="dashboard-button dashboard-button-secondary" href="{{ route('liquidations.edit', $liquidation) }}">Edit</a>@endcan
        @can('archive', $liquidation) @if (! $liquidation->isArchived())<form id="archive-liquidation-form" method="POST" action="{{ route('liquidations.archive', $liquidation) }}">@csrf</form><button class="dashboard-button dashboard-button-secondary" type="button" onclick="document.getElementById('archive-liquidation-modal').showModal()">Archive</button>@endif @endcan
        @can('restore', $liquidation) @if ($liquidation->isArchived())<form id="restore-liquidation-form" method="POST" action="{{ route('liquidations.restore', $liquidation) }}">@csrf</form><button class="dashboard-button dashboard-button-secondary" type="button" onclick="document.getElementById('restore-liquidation-modal').showModal()">Restore</button>@endif @endcan
        @can('approve', $liquidation) @if ($liquidation->isPending())<form method="POST" action="{{ route('liquidations.approve', $liquidation) }}">@csrf<button class="dashboard-button" type="submit">Approve</button></form><button class="dashboard-button dashboard-button-secondary" type="button" data-modal-open="liquidation-reject-modal">Reject</button>@endif @endcan
        @can('delete', $liquidation)<form id="delete-liquidation-form" method="POST" action="{{ route('liquidations.destroy', $liquidation) }}">@csrf @method('DELETE')</form><button class="dashboard-button dashboard-button-secondary" type="button" onclick="document.getElementById('delete-liquidation-modal').showModal()">Delete</button>@endcan
    </div>
    @can('reject', $liquidation) @if ($liquidation->isPending())<x-ui.reject-modal id="liquidation-reject-modal" :action="route('liquidations.reject', $liquidation)" subject="liquidation report" />@endif @endcan
    @can('archive', $liquidation) @if (! $liquidation->isArchived())<dialog id="archive-liquidation-modal" class="reject-modal"><div class="reject-modal-content"><h2>Archive report?</h2><p>The report leaves Published and keeps its approval state.</p><div class="reject-modal-actions"><button type="button" class="dashboard-button dashboard-button-secondary" onclick="document.getElementById('archive-liquidation-modal').close()">Cancel</button><button type="submit" form="archive-liquidation-form" class="dashboard-button">Archive</button></div></div></dialog>@endif @endcan
    @can('restore', $liquidation) @if ($liquidation->isArchived())<dialog id="restore-liquidation-modal" class="reject-modal"><div class="reject-modal-content"><h2>Restore report?</h2><p>Its approval state will stay unchanged.</p><div class="reject-modal-actions"><button type="button" class="dashboard-button dashboard-button-secondary" onclick="document.getElementById('restore-liquidation-modal').close()">Cancel</button><button type="submit" form="restore-liquidation-form" class="dashboard-button">Restore</button></div></div></dialog>@endif @endcan
    @can('delete', $liquidation)<dialog id="delete-liquidation-modal" class="reject-modal"><div class="reject-modal-content"><h2>Delete report permanently?</h2><p>This also removes its private PDF file and cannot be undone.</p><div class="reject-modal-actions"><button type="button" class="dashboard-button dashboard-button-secondary" onclick="document.getElementById('delete-liquidation-modal').close()">Cancel</button><button type="submit" form="delete-liquidation-form" class="dashboard-button">Delete permanently</button></div></div></dialog>@endcan
</div>
@endsection
